### ISSUE TITLE
Modelo de Negocios

### ISSUE THREAD

**Issue by IsraelNicolas61** [SistemasTecTlaxiaco/practica-de-modelo-de-negocios-alfa-dinamita#2]
[Modelo de Negocios.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-modelo-de-negocios-alfa-dinamita/files/7341431/Modelo.de.Negocios.pdf)

**Comment by scristianj** [comment]
18%

**Comment by josealfredo79** [comment]
Falta la propuesta de valor y el modelo canvas...

**Comment by josealfredo79** [comment]
Hay qye complementarlo porque no se revisa...si no se termina...

**Comment by josealfredo79** [comment]
Bien hecho y revisado
